-- 1. Invoice Header Table
-- Stores metadata and totals for each invoice
CREATE OR REPLACE TABLE LLE_INVOICE_HEADER (
    INVOICE_NUMBER VARCHAR PRIMARY KEY,
    VENDOR_NAME VARCHAR,
    INVOICE_DATE DATE,
    SUBTOTAL NUMERIC(18,2),
    TAX NUMERIC(18,2),
    TOTAL_AMOUNT_DUE NUMERIC(18,2),
    CUSTOMER_ID VARCHAR,
    SHIP_TO_ADDRESS VARCHAR,
    EXTRA_DETAILS VARIANT,
    PROCESSED_DATE DATE
);

COMMENT ON TABLE LLE_INVOICE_HEADER IS 'Stores metadata and totals for each invoice';
COMMENT ON COLUMN LLE_INVOICE_HEADER.INVOICE_NUMBER IS 'Unique identifier for the invoice';
COMMENT ON COLUMN LLE_INVOICE_HEADER.VENDOR_NAME IS 'Vendor name';
COMMENT ON COLUMN LLE_INVOICE_HEADER.INVOICE_DATE IS 'Invoice date';
COMMENT ON COLUMN LLE_INVOICE_HEADER.SUBTOTAL IS 'Pre-tax total';
COMMENT ON COLUMN LLE_INVOICE_HEADER.TAX IS 'Tax amount';
COMMENT ON COLUMN LLE_INVOICE_HEADER.TOTAL_AMOUNT_DUE IS 'Final amount due';
COMMENT ON COLUMN LLE_INVOICE_HEADER.CUSTOMER_ID IS 'Customer identifier';
COMMENT ON COLUMN LLE_INVOICE_HEADER.SHIP_TO_ADDRESS IS 'Delivery address';
COMMENT ON COLUMN LLE_INVOICE_HEADER.EXTRA_DETAILS IS 'Semi-structured data for unique fields';
COMMENT ON COLUMN LLE_INVOICE_HEADER.PROCESSED_DATE IS 'Date the invoice was processed and uploaded into Snowflake';

-- 2. Invoice Line Items Table
-- Stores individual charges/items from invoices as separate records
CREATE OR REPLACE TABLE LLE_INVOICE_LINE_ITEMS (
    INVOICE_NUMBER VARCHAR,
    WELL_NAME VARCHAR,
    ITEM_DESCRIPTION VARCHAR,
    QUANTITY NUMERIC(18,2),
    UNIT_PRICE NUMERIC(18,2),
    LINE_TOTAL NUMERIC(18,2),
    EXTRA_DETAILS VARIANT,
    FOREIGN KEY (INVOICE_NUMBER) REFERENCES INVOICE_HEADER(INVOICE_NUMBER)
);

COMMENT ON TABLE LLE_INVOICE_LINE_ITEMS_ITEMS IS 'Stores individual charges/items from invoices as separate records';
COMMENT ON COLUMN LLE_INVOICE_LINE_ITEMS.INVOICE_NUMBER IS 'Links to the parent invoice (foreign key)';
COMMENT ON COLUMN INVOLLE_INVOICE_LINE_ITEMSICE_LINE_ITEMS.WELL_NAME IS 'Extracted from line items or dedicated fields';
COMMENT ON COLUMN LLE_INVOICE_LINE_ITEMS.ITEM_DESCRIPTION IS 'Product/service description';
COMMENT ON COLUMN LLE_INVOICE_LINE_ITEMS.QUANTITY IS 'Quantity purchased';
COMMENT ON COLUMN LLE_INVOICE_LINE_ITEMS.UNIT_PRICE IS 'Price per unit';
COMMENT ON COLUMN LLE_INVOICE_LINE_ITEMS.LINE_TOTAL IS 'Calculated as QUANTITY * UNIT_PRICE';
COMMENT ON COLUMN LLE_INVOICE_LINE_ITEMS.EXTRA_DETAILS IS 'Non-standard fields';

-- 3. Statements Table
-- Stores high-level metadata from each statement
CREATE OR REPLACE TABLE LLE_STATEMENTS (
    STATEMENT_ID VARCHAR PRIMARY KEY,
    VENDOR_NAME VARCHAR,
    CUSTOMER_NAME VARCHAR,
    STATEMENT_DATE DATE,
    TOTAL_AMOUNT_DUE NUMERIC(18,2),
    CURRENT_AMOUNT NUMERIC(18,2),
    PAST_DUE_1_30 NUMERIC(18,2),
    PAST_DUE_31_60 NUMERIC(18,2),
    PAST_DUE_61_90 NUMERIC(18,2),
    PAST_DUE_OVER_90 NUMERIC(18,2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

COMMENT ON TABLE LLE_STATEMENTS IS 'Stores high-level metadata from each statement';
COMMENT ON COLUMN LLE_STATEMENTS.STATEMENT_ID IS 'Unique identifier for the statement (e.g., hash of vendor + date)';
COMMENT ON COLUMN LLE_STATEMENTS.VENDOR_NAME IS 'Vendor name';
COMMENT ON COLUMN LLE_STATEMENTS.CUSTOMER_NAME IS 'Customer name (for this table it will always be Lucky Lad Energy)';
COMMENT ON COLUMN LLE_STATEMENTS.STATEMENT_DATE IS 'Statement date';
COMMENT ON COLUMN LLE_STATEMENTS.TOTAL_AMOUNT_DUE IS 'Total outstanding balance';
COMMENT ON COLUMN LLE_STATEMENTS.CURRENT_AMOUNT IS 'Amount not yet overdue';
COMMENT ON COLUMN LLE_STATEMENTS.PAST_DUE_1_30 IS '1-30 days overdue';
COMMENT ON COLUMN LLE_STATEMENTS.PAST_DUE_31_60 IS '31-60 days overdue';
COMMENT ON COLUMN LLE_STATEMENTS.PAST_DUE_61_90 IS '61-90 days overdue';
COMMENT ON COLUMN LLE_STATEMENTS.PAST_DUE_OVER_90 IS 'Over 90 days overdue';
COMMENT ON COLUMN LLE_STATEMENTS.CREATED_AT IS 'Timestamp of record creation';
COMMENT ON COLUMN LLE_STATEMENTS.UPDATED_AT IS 'Timestamp of last update';

-- 4. Statement Transactions Table
-- Stores individual transactions listed in statements
CREATE OR REPLACE TABLE LLE_STATEMENT_TRANSACTIONS (
    TRANSACTION_ID VARCHAR PRIMARY KEY,
    STATEMENT_ID VARCHAR,
    TRANSACTION_DATE DATE,
    DESCRIPTION VARCHAR,
    AMOUNT NUMERIC(18,2),
    BALANCE_AFTER NUMERIC(18,2),
    DUE_DATE DATE,
    ORGINAL_AMOUNT NUMERIC(18,2),
    WELL_NAME VARCHAR,
    TRANSACTION_TYPE VARCHAR,
    FOREIGN KEY (STATEMENT_ID) REFERENCES STATEMENTS(STATEMENT_ID)
);

COMMENT ON TABLE LLE_STATEMENT_TRANSACTIONS IS 'Stores individual transactions listed in statements';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.TRANSACTION_ID IS 'Unique identifier for the transactions';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.STATEMENT_ID IS 'Foreign key linking to statements.STATEMENT_ID';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.TRANSACTION_DATE IS 'Date of the transaction';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.DESCRIPTION IS 'Transaction details';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.AMOUNT IS 'Transaction Amount';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.BALANCE_AFTER IS 'Running balance after the transaction';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.DUE_DATE IS 'Due date parsed from the description';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.ORGINAL_AMOUNT IS 'Original amount from the description';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.WELL_NAME IS 'Associated Well';
COMMENT ON COLUMN LLE_STATEMENT_TRANSACTIONS.TRANSACTION_TYPE IS 'Type (e.g., INVOICE, JOURNAL_REVERSAL, CREDIT_TRANSFER)';

-- 5. Invoice Line Items View with Processing Date
-- Creates a view that joins line items with their header information including processing date
CREATE OR REPLACE VIEW OCCLUSION.WELLS.LLE_INVOICE_LINE_ITEMS_WITH_DATES AS
SELECT
    l.*,
    h.INVOICE_DATE,
    h.PROCESSED_DATE
FROM
    LLE_INVOICE_LINE_ITEMS l
JOIN
    LLE_INVOICE_HEADER h ON l.INVOICE_NUMBER = h.INVOICE_NUMBER;

COMMENT ON VIEW LLE_INVOICE_LINE_ITEMS_WITH_DATES IS 'View that joins line items with their header information including dates for easier searching';